export default {
  signin: {
    title: 'Melden Sie sich bei Uniq Alpha an',
    googleButton: 'Mit Google anmelden',
    emailButton: 'Mit E-Mail oder Telefonnummer fortfahren',
    description: 'oder',
    username: 'Benutzername',
    password: 'Passwort',
    signin: 'Anmelden',
    signup: 'Registrieren',
    continue: 'Fortfahren',
    forgotPassword: 'Passwort vergessen?',
    haveAccount: 'Haben Sie kein Konto?',
    signinByEmail: 'Mit E-Mail anmelden',
    email: 'E-Mail',
    enterPassword: 'Geben Sie Ihr Passwort ein.',
    signinWithDisposablePassword: 'Mit einem Einwegpasswort anmelden',
    requiredEmail: 'E-Mail wird benötigt',
    invalidEmail: 'Ungültige E-Mail',
    minPassword: 'Das Passwort muss mindestens 8 Zeichen lang sein',
    requiredPassword: 'Familienname wird benötigt',
  },
  signup: {
    title: 'Registrieren bei Uniq Alpha',
    firstName: 'Vorname',
    lastName: 'Nachname',
    requiredName: 'Vorname wird benötigt',
    requiredLastName: 'Nachname wird benötigt',
    requiredEmail: 'E-Mail wird benötigt',
    invalidEmail: 'Ungültige E-Mail',
    minPassword: 'Das Passwort muss mindestens 8 Zeichen lang sein',
    emailAndPhone: 'E-Mail',
    password: 'Passwort',
    phoneNumber: 'Telefon nummer',
    Privacy:
      'Ich stimme den Nutzungsbedingungen, der Datenschutzrichtlinie und den Standardbenachrichtigungseinstellungen von UniqAlpha zu.',
    createAccount: 'Konto erstellen',
    haveAccount: 'Haben Sie bereits ein Konto?',
    signin: 'Anmelden',
    GoogleButton: 'Mit Google anmelden',
    emailOrPhone: 'Mit E-Mail oder Telefonnummer fortfahren',
    description:
      'Durch die Erstellung eines Kontos stimmen Sie unseren Nutzungsbedingungen, der Datenschutzrichtlinie und unseren Standardbenachrichtigungseinstellungen zu.',
    uppercaseAndLowercaseLetters: 'Enthält Groß- und Kleinbuchstaben',
    IncludesNumber: 'Enthält Zahlen',
    includeSpecialCharacters: 'Enthält Sonderzeichen(@,!,*,...)',
    requiredPassword: 'Passwort wird benötigt',
    userType: 'Benutzertyp',
  },

  forgotPassword: {
    title: 'Passwort vergessen?',
    description:
      'Geben Sie die E-Mail-Adresse oder Telefonnummer ein, die Sie bei der Anmeldung verwendet haben, und wir senden Ihnen Anweisungen zum Zurücksetzen Ihres Passworts.',
    security:
      'Aus Sicherheitsgründen speichern wir Ihr Passwort nicht. Seien Sie versichert, dass wir Ihr Passwort niemals per E-Mail oder Telefonnummer versenden.',
    email: 'E-Mail',
    sendResetInstructions: 'Anweisungen zum Zurücksetzen senden',
    invalidEmail: 'Ungültige E-Mail',
    requiredEmail: 'E-Mail wird benötigt',
    request: 'Anfrage zum Zurücksetzen des Passworts erfolgreich gesendet',
    back: 'Zurück zur Startseite',
  },
  newPassword: {
    title: 'Neues Passwort',
    uppercaseAndLowercaseLetters: 'Enthält Groß- und Kleinbuchstaben',
    IncludesNumber: 'Enthält Zahlen',
    eightCharacters: 'Mindestens acht Zeichen lang',
    VerifyButton: 'Überprüfen und eingeben',
    newPassword: 'Neues Passwort',
    repeatNewPassword: 'Neues Passwort wiederholen',
    minPassword: 'Das Passwort muss mindestens 8 Zeichen lang sein',
    requiredPassword: 'Passwort wird benötigt',
    passwordsDontMatch: 'Passwörter stimmen nicht überein',
    includeSpecialCharacters: 'Enthält Sonderzeichen(@,!,*,...)',
  },
  otp: {
    subTitle: 'Zugriffsprüfung',
    title: 'Geben Sie Ihren Bestätigungscode ein',
    enterYourCode: 'Geben Sie den Code ein',
    resendCode: 'Code erneut senden',
    signinButton: 'Anmelden',
  },

  HomePage: {
    title: 'Hallo Welt!',
    about: 'Zur Info-Seite',
    FrequentlyAskedQuestions: 'Häufig gestellte Fragen',
  },
  AboutPage: {
    title: 'Dies ist die Über-Seite',
  },
  Header: {
    login: 'Einloggen / Registrieren',
    Account: 'Mein Konto',
    Home: 'Startseite',
    Advertisement: 'Anzeige',
    Favorites: 'Favoriten',
    profile: 'Profil',
    search: 'Suchen',
    ManufacturerAndModel: 'Hersteller, Modell',
    CityStateOrCountry: 'Stadt, Staat oder Land',
    Language: 'Sprache',
    Category: 'Kategorie',
    SellOnUniqAlpha: 'Auf UA verkaufen',
    Filter: 'Filter',
    Message: 'Nachricht',
  },
  Hero: {
    BuildingTheFutureWith: 'Die Zukunft gestalten mit',
    IndustrialEquipment: 'Industriellen Geräten',
    Provide: 'Wir bieten hochwertige Industriemaschinen',
    Help: 'um Ihrem Unternehmen beim Wachstum und Erfolg zu helfen.',
  },
  Categories: {
    Categories: 'Kategorien',
  },
  Advertisement: {
    Advertisement: 'Anzeige',
  },
  AboutUs: {
    About: 'Über',
    Us: 'Uns',
    LearnMore: 'Mehr erfahren',
  },
  ButtonText: {
    View: 'Ansehen',
    ViewAll: 'Alle anzeigen',
  },
  Explore: {
    Sell: 'Verkaufen Sie Ihre Maschinen',
    Fast: 'Schnell posten',
    Explore: 'Jetzt entdecken',
  },
  FAQ: {
    Title: 'Häufig gestellte Fragen',
  },
  Footer: {
    About: 'Über uns',
    Contact: 'Kontaktieren Sie uns',
    Blog: 'Blog',
    Testimonials: 'Erfahrungsberichte',
    Media: 'Medien',
    Sell: 'Verkaufen Sie mit uns',
    uniq: 'Uniq Alpha System',
    Seller: 'Werden Sie Verkäufer',
    SellerBlog: 'Verkäufer Blog',
    search: 'Suchen',
    ManufacturerAndModel: 'Hersteller, Modell',
    CityStateOrCountry: 'Stadt, Staat oder Land',
    Company: 'Unternehmen',
  },
  Admin: {
    yourPhoneNumber: 'Ihre Telefonnummer',
    login: 'Login',
    getOtp: 'OTP anfordern',
  },
  Users: {
    name: 'Name',
    lastName: 'Nachname',
    email: 'E-Mail',
    phone: 'Telefon',
    filter: 'Filter',
    search: 'Suchen',
    removeFilter: 'Filter entfernen',
    searchFirstName: 'Suche nach Vorname',
    searchLastName: 'Suche nach Nachname',
    searchPhone: 'Suche nach Telefon',
    searchEmail: 'Suche nach E-Mail',
  },
  Toast: {
    copyTextSuccess: 'Text erfolgreich kopiert',
  },
  SellerInformation: {
    ContactInformation: 'Kontaktinformationen',
    message: 'Nachricht an den Verkäufer',
  },
  SellerProfile: {
    AddCommentTitle: 'Schreiben Sie Ihre Kommentare zu dieser Anzeige',
    AddCommaButton: 'Einen Kommentar hinzufügen',
    UserComments: 'Benutzerkommentare',
    UserAdvertisement: 'Benutzeranzeige',
    SellerAddCommaModal: {
      title: 'Einen Kommentar hinzufügen',
      description:
        'Ihre Meinung hilft uns und anderen Nutzern, die beste Wahl zu treffen',
      WriteYourReview: 'Schreiben Sie Ihre Bewertung über den Verkäufer',
      TextAreaPlaceHolder: 'Beschreibung',
      SubmitButton: 'Kommentar abgeben',
    },
  },
  SellOnUniq: {
    selectPhoto: {
      title: 'Foto auswählen',
      description:
        'Ein gutes Bild kann mehr Kunden anziehen! Fügen Sie ein Foto hinzu, um Ihre Anzeige hervorzuheben',
      addPhotosForAd: 'Fotos hinzufügen, um Ihre Anzeige hervorzuheben',
      addPhoto: 'Foto hinzufügen',
    },
    ToggleForm: {
      title: 'Kontakttelefonnummer in der Anzeige ausblenden',
    },
    UserType: {
      title: 'Benutzertyp',
      Person: 'Person',
      Company: 'Unternehmen',
    },
    RegisterButtons: {
      RegisterAnAd: 'Anzeige registrieren',
      Cancellation: 'Stornierung',
    },
    AdvertisementRegistrationForm: {
      AdvertisementRegistration: 'Anzeige registrieren',
      Category: 'Kategorie',
      AdvertisementTitle: 'Anzeigentitel',
    },
  },
  SingleAd: {
    BrandModel: 'Marke & Modell',
    Year: 'Baujahr',
    SpindlePower: 'Spindelleistung',
    ControlType: 'Steuerungstyp (Manuell/CNC)',
    Axes: 'Achsen',
    PrecisionTolerance: 'Präzision & Toleranz',
    Condition: 'Zustand (Neu / Gebraucht)',
    Warranty: 'Garantiestatus (Optional)',
    LastServiceDate: 'Letztes Service-Datum (Optional)',
    OperatingHoursUsage: 'Betriebsstunden / Nutzung (Optional)',
    Location: 'Standort',
    Price: 'Preis',
    Description: 'Beschreibung',
    RelatedAdvertisement: 'Verwandte Anzeige',
  },
  UserProfile: {
    UserProfileItem: {
      MyProfile: 'Mein Profil',
      MyAds: 'Meine Anzeige',
      MyFavorites: 'Meine Lieblingsanzeigen',
      Support: 'Support',
      ResetPass: 'Passwort zurücksetzen',
      DeleteAccount: 'Konto löschen',
      LogOut: 'Vom Konto abmelden',
    },
    MyProfile: {
      Add: 'Hinzufügen',
      Photo: 'Foto',
      Username: 'Benutzername',
      Name: 'Vorname',
      LastName: 'Nachname',
      DateOfBirth: 'Geburtsdatum',
      email: 'E-Mail',
      phoneNumber: 'Telefonnummer',
      CompanyName: 'Firmenname',
      Country: 'Land',
      City: 'Stadt',
      Address: 'Adresse',
      zipCode: 'Postleitzahl',
      submitButton: 'Profil aktualisieren',
      invalidEmail: 'Ungültige E-Mail',
      UserNameRequirement: 'Benutzername wird benötigt',
      NameRequirement: 'Vorname wird benötigt',
      LastNameRequirement: 'Nachname wird benötigt',
      EmailRequirement: 'E-Mail wird benötigt',
      PhoneRequirement: 'Telefonnummer wird benötigt',
    },
    MyAds: {
      ApprovedAds: 'Genehmigt',
      RejectedAds: 'Abgelehnt',
      PendingAds: 'Ausstehend',
      RemoveModalTitle: 'Aus der Liste entfernen',
      ModalDescription:
        'Sind Sie sicher, dass Sie die Anzeige löschen möchten?',
      ModalRemoveButton: 'Ja, löschen',
      ModalCancelButton: 'Abbrechen',
    },

    FavoriteAdvertisement: {
      FavoriteAdvertisement: 'Lieblingsanzeige',
      HaveNotFavoriteAd: 'Sie haben derzeit keine Lieblingsanzeigen',
      RemoveModalTitle: 'Aus der Lesezeichenliste entfernen',
      ModalDescription:
        'Sind Sie sicher, dass Sie die Anzeige aus der Favoritenliste löschen möchten?',
      ModalRemoveButton: 'Ja, löschen',
      ModalCancelButton: 'Abbrechen',
    },
    Support: {
      ContactSupport: 'Support kontaktieren',
      description:
        'Teilen Sie Ihre Fragen und Kommentare mit dem Uniq Alpha Support',
      Subject: 'Betreff',
      SubjectPlaceholder: 'Geben Sie den Betreff der Nachricht an',
      YourMessage: 'Ihre Nachricht',
      YourMessagePlaceholder: 'Geben Sie Ihre Nachricht ein',
      SendButton: 'Senden',
    },
    ResetPass: {
      ResetPass: 'Passwort zurücksetzen',
      description:
        'Ihr Passwort muss mindestens 6 Zeichen lang sein und eine Kombination aus Zahlen, Buchstaben und Sonderzeichen (!$@%) enthalten.',
      CurrentPassword: 'Aktuelles Passwort',
      NewPassword: 'Neues Passwort',
      ReTypeNewPassword: 'Neues Passwort erneut eingeben',
      ForgotPass: 'Passwort vergessen?',
      LogOutOtherDevicesMessage:
        'Von anderen Geräten abmelden. Wählen Sie dies, wenn jemand anderes Ihr Konto verwendet hat.',
      ChangePass: 'Passwort ändern',
    },
    DeleteAccount: {
      DeleteAccount: 'Konto löschen',
      PermanentlyDeleteAccount: 'Konto dauerhaft löschen',
      description:
        'Es tut uns leid, Sie gehen zu sehen! Bitte lesen Sie vor dem Fortfahren die folgenden wichtigen Informationen sorgfältig durch, um die Konsequenzen dieser Aktion vollständig zu verstehen.',
      deletingYourAccountMean: 'Was bedeutet es, Ihr Konto zu löschen?',
      PermanentDataDeletion:
        'Permanente Datenlöschung: Alle Ihre persönlichen Daten, einschließlich Benutzername, E-Mail-Adresse, Kontoeinstellungen und zugehörige Inhalte, werden dauerhaft aus unserem System entfernt.',
      LossOfAccess:
        'Verlust des Zugriffs: Sobald Ihr Konto gelöscht ist, haben Sie keinen Zugriff mehr auf Ihr Profil, Ihre Aktivitätsgeschichte, Transaktionen oder gespeicherte Inhalte.',
      IrreversibleAction:
        'Irreversible Aktion: Dieser Prozess ist unumkehrbar, und nach der Bestätigung kann Ihr Konto nicht wiederhergestellt werden.',
      ConsiderBeforeDeleting:
        'Bitte überlegen Sie vor dem Löschen Ihres Kontos',
      SupportHelp:
        'Wenn Sie Probleme oder Bedenken haben, steht Ihnen unser Support-Team gerne zur Verfügung.',
      ContactSupport: '[Support kontaktieren]',
      TemporaryDeactivation:
        'Wenn Sie nur eine Pause benötigen, können Sie Ihr Konto vorübergehend deaktivieren und später zurückkehren.',
      FinalConfirmation: 'Endgültige Bestätigung',
      ConfirmDeletionMessage:
        'Durch das Löschen Ihres Kontos bestätigen Sie, dass Sie die Konsequenzen vollständig verstehen und der dauerhaften Entfernung Ihrer Daten zustimmen.',
      ConfirmDeleteCheckbox:
        'Ja, ich verstehe, dass diese Aktion dauerhaft ist und ich stimme zu, mein Konto zu löschen.',
      DeleteAccountButton: 'Konto löschen',
    },
  },
};
